
### Get location components
GET http://localhost:7071/api/location-components
    ?lid=d8c315a6-2288-3eee-4c2c-4773a46b782e
content-type: application/json
Cookie: HFI_ALFRED_AUTH_TOKEN=1c48231c-ca48-4873-96b2-a0371a10cbc3


### No auth call
GET http://localhost:7071/api/location-components-data
    ?location_id=afc0ef89-119a-409e-9c02-a7a048786062
content-type: application/json