### Good request

POST http://localhost:7071/api/back-office-association-code
content-type: application/json
Cookie: HFI_ALFRED_AUTH_TOKEN=2bcbc3b0-4ddd-4ad8-b6b9-ac5e01a08b5b

{
    "location_id": "df557bad-c51f-40a6-cb54-73aa3bdf6f98"
}

### Bad request: Invalid location_id

POST http://localhost:7071/api/back-office-association-code
content-type: application/json
Cookie: HFI_ALFRED_AUTH_TOKEN=87d38ab6-bd8a-4dca-89b7-87e750b2c9a0

{
    "location_id": "b7732562-c457-47f0-921d-f69bbc487983"
}

### Bad request: Missing location_id

POST http://localhost:7071/api/back-office-association-code
content-type: application/json
Cookie: HFI_ALFRED_AUTH_TOKEN=87d38ab6-bd8a-4dca-89b7-87e750b2c9a0


### Working prod example

POST https://alfred-api.hydraflexinc.com/alfred/back-office-association-code
content-type: application/json
Cookie: HFI_ALFRED_AUTH_TOKEN=87d38ab6-bd8a-4dca-89b7-87e750b2c9a0

{
    "location_id": "afc0ef89-119a-409e-9c02-a7a048786062"
}

### No auth request

POST http://localhost:7071/api/back-office-association-code-data
content-type: application/json
Cookie: HFI_ALFRED_AUTH_TOKEN=2bcbc3b0-4ddd-4ad8-b6b9-ac5e01a08b5b

{
    "location_id": "df557bad-c51f-40a6-cb54-73aa3bdf6f98"
}