### Normal simple working, individual readings

GET http://localhost:7071/api/flow-sense-gpm
    ?gatewayId=advm2-sensor-trial
content-type: application/json
Cookie: HFI_ALFRED_AUTH_TOKEN=1c48231c-ca48-4873-96b2-a0371a10cbc3

### Trigger dev mode
GET http://localhost:7071/api/flow-sense-gpm
    ?gatewayId=advm2-sensor-trial
    &start=2021-09-01T00:00:00Z
    &end=2021-09-01T00:00:01Z
    &dev=true
content-type: application/json
Cookie: HFI_ALFRED_AUTH_TOKEN=1c48231c-ca48-4873-96b2-a0371a10cbc3

### Normal simple working, timebucketed

GET http://localhost:7071/api/flow-sense-gpm
    ?gatewayId=advm2-sensor-trial
    &bucketMinutes=60
content-type: application/json
Cookie: HFI_ALFRED_AUTH_TOKEN=1c48231c-ca48-4873-96b2-a0371a10cbc3

### No auth call
GET http://localhost:7071/api/flow-sense-gpm-data
    ?gatewayId=advm2-sensor-trial
content-type: application/json