### Simple call

POST http://localhost:7071/api/user-update-notification
content-type: application/json
Cookie: HFI_ALFRED_AUTH_TOKEN=1c48231c-ca48-4873-96b2-a0371a10cbc3

{
    "wants_email": false,
    "wants_push": false
}