### Simple, no auth

GET http://localhost:7071/api/vanity-stats
content-type: application/json


### Simple, with HEAD

HEAD http://localhost:7071/api/vanity-stats
content-type: application/json


### Prod, no auth

GET https://alfred-api.hydraflexinc.com/alfred/vanity-stats
content-type: application/json


