### Simple, no auth

GET http://localhost:7071/api/vanity-stats
content-type: application/json


### Prod, no auth

GET https://alfred-api.hydraflexinc.com/alfred-v2/vanity-stats
content-type: application/json


### Uptime Robot

HEAD https://alfred-api.hydraflexinc.com/alfred-v2/vanity-stats
content-type: application/json


