# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
#
# TODO Azure/functions-action has been downgraded to v1.3.1 in order to fix this issue. Restore after fix.
# https://github.com/Azure/functions-action/issues/86

name: PRODUCTION - Build and deploy Node.js project to Azure Function App

on:
  release:
    types: [created]

env:
  AZURE_FUNCTIONAPP_NAME: "alfred-external"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # root
  NODE_VERSION: "20.x"
  CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Resolve Project Dependencies Using Npm"
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1.3.1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          slot-name: "production"

  purge-edge-cache:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Cloudflare Purge Cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
